<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>week-7-demo – CMSC 2208 : Introduction to Machine Learning</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b758ccaa5987ceb1b75504551e579abf.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-b337f537912f5ab074b938eebad4c5d7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-feb0c0ed7aac57d66ec8dce0f6a48183.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-b337f537912f5ab074b938eebad4c5d7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../shared/assets/course.css">
<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed fullcontent quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">CMSC 2208 : Introduction to Machine Learning</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Week 7 Demo: Uncertainty Estimates from Classifiers</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
        <div class="sidebar-tools-collapse">
    <a href="https://discord.gg/az8cmeqJdc" title="" class="quarto-navigation-tool px-1" aria-label="Discord"><i class="bi bi-chat-dots"></i></a>
    <a href="https://sctcc.learn.minnstate.edu/d2l/login" title="" class="quarto-navigation-tool px-1" aria-label="D2L"><i class="bi bi-book-half"></i></a>
</div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Course information</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course/syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course/schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/policies/office-hours.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Office Hours</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/policies/homework-coursework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment Policies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/policies/general-policies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">General Policies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/policies/ai-policy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AI Policy</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Weekly Overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weekly-overview/week-06/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 6 (Starts - 16 FEB)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weekly-overview/week-07/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 7 (Starts - 23 FEB)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Weekly Assignments</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../assignments/week-06/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 6 (Starts - 16 FEB)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../assignments/week-07/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 7 (Starts - 23 FEB)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Guides</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 1</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/guides/setup/miniconda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Miniconda Setup</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/guides/setup/jupyter-learning-links.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Jupyter Learning Links</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 2</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/guides/cmsc-2208/week-02/cmsc-2208-chap-02-learning-resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2 Week 2 Reference Videos</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 3</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/guides/cmsc-2208/week-03/cmsc-2208-chap-02-learining-resources-week-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2 Week 3 Reference Videos</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 7 Demo: Uncertainty Estimates from Classifiers</h1>
</div>



<div class="quarto-title-meta">

    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">February 16, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>So far in this course, every time we’ve used a classifier, we’ve asked one question: <strong>what does the model predict?</strong> We call <code>.predict()</code> and get back a label (“pass” or “fail,” “stay” or “churn”). We call <code>.score()</code> and get back a single accuracy number that tells us how often those predictions are correct.</p>
<p>But <code>.predict()</code> only gives us the model’s final answer. It doesn’t tell us how confident the model is in that answer. Consider two students who are both predicted to fail:</p>
<ul>
<li><strong>Student A:</strong> The model is 95% sure this student will fail</li>
<li><strong>Student B:</strong> The model is 52% sure this student will fail</li>
</ul>
<p><code>.predict()</code> returns “fail” for both students, but these are very different situations. Student A shows clear signs of struggling, while Student B is essentially a coin flip. If you were an academic advisor deciding who to contact for extra support, you’d probably treat these two students very differently, and you’d want to know which situation you’re dealing with.</p>
<p>This week, we learn how to ask classifiers a richer question: <strong>how confident are you in each prediction?</strong> Scikit-learn provides two methods for this:</p>
<ul>
<li><strong><code>predict_proba</code></strong> returns probability estimates (values between 0 and 1 that are easy to interpret)</li>
<li><strong><code>decision_function</code></strong> returns raw confidence scores (values on an arbitrary scale that are harder to interpret)</li>
</ul>
<p>Both go beyond the simple yes/no answer of <code>.predict()</code> and reveal the model’s level of certainty.</p>
<section id="what-this-demo-covers" class="level3">
<h3 class="anchored" data-anchor-id="what-this-demo-covers">What This Demo Covers</h3>
<p>This demo covers: - Using <code>predict_proba</code> to get probability estimates for each class - Interpreting what the probability columns mean and how they relate to <code>.predict()</code> - Using <code>decision_function</code> to get raw confidence scores - Understanding the difference between <code>predict_proba</code> and <code>decision_function</code> - Why prediction confidence matters for real-world decisions</p>
<p>The textbook then shows you: - These methods applied to GradientBoostingClassifier with 2D visualizations - How uncertainty estimates extend to multiclass problems (more than two classes) - The concept of model calibration (when reported probabilities match actual outcomes) - A complete summary of all supervised learning algorithms from Chapter 2</p>
</section>
</section>
<section id="part-1-creating-the-dataset" class="level2">
<h2 class="anchored" data-anchor-id="part-1-creating-the-dataset">Part 1: Creating the Dataset</h2>
<p>This section uses the same student performance dataset from Weeks 3 and 5. Using the same dataset lets us focus on the new methods without learning a new domain.</p>
<div id="07dea3c5" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create reproducible random data</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">42</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">300</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"attendance"</span>: rng.integers(<span class="dv">60</span>, <span class="dv">101</span>, n),</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"homework_rate"</span>: rng.integers(<span class="dv">50</span>, <span class="dv">101</span>, n),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"quiz_avg"</span>: rng.integers(<span class="dv">40</span>, <span class="dv">101</span>, n),</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"exam_avg"</span>: rng.integers(<span class="dv">40</span>, <span class="dv">101</span>, n),</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Create final score with a realistic formula plus noise</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>base_score <span class="op">=</span> (<span class="fl">0.2</span><span class="op">*</span>df[<span class="st">"homework_rate"</span>] <span class="op">+</span> <span class="fl">0.3</span><span class="op">*</span>df[<span class="st">"quiz_avg"</span>] <span class="op">+</span> <span class="fl">0.5</span><span class="op">*</span>df[<span class="st">"exam_avg"</span>])</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>noise <span class="op">=</span> rng.normal(<span class="dv">0</span>, <span class="dv">5</span>, n)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"final_score"</span>] <span class="op">=</span> (base_score <span class="op">+</span> noise).<span class="bu">round</span>(<span class="dv">0</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Create pass/fail classification target</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"pass_fail"</span>] <span class="op">=</span> np.where(df[<span class="st">"final_score"</span>] <span class="op">&gt;=</span> <span class="dv">70</span>, <span class="st">"pass"</span>, <span class="st">"fail"</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Dataset size: </span><span class="sc">{</span><span class="bu">len</span>(df)<span class="sc">}</span><span class="ss"> students"</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Features: attendance, homework_rate, quiz_avg, exam_avg"</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Target: pass_fail (pass if final_score &gt;= 70, otherwise fail)</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Class distribution:"</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">"pass_fail"</span>].value_counts())</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>df.head(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Dataset size: 300 students
Features: attendance, homework_rate, quiz_avg, exam_avg
Target: pass_fail (pass if final_score &gt;= 70, otherwise fail)

Class distribution:
pass_fail
pass    157
fail    143
Name: count, dtype: int64
</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">attendance</th>
<th data-quarto-table-cell-role="th">homework_rate</th>
<th data-quarto-table-cell-role="th">quiz_avg</th>
<th data-quarto-table-cell-role="th">exam_avg</th>
<th data-quarto-table-cell-role="th">final_score</th>
<th data-quarto-table-cell-role="th">pass_fail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>63</td>
<td>68</td>
<td>77</td>
<td>40</td>
<td>63.0</td>
<td>fail</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>91</td>
<td>92</td>
<td>87</td>
<td>42</td>
<td>64.0</td>
<td>fail</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>86</td>
<td>50</td>
<td>85</td>
<td>53</td>
<td>64.0</td>
<td>fail</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>77</td>
<td>95</td>
<td>48</td>
<td>93</td>
<td>68.0</td>
<td>fail</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>77</td>
<td>77</td>
<td>90</td>
<td>67</td>
<td>70.0</td>
<td>pass</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>95</td>
<td>57</td>
<td>72</td>
<td>83</td>
<td>73.0</td>
<td>pass</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>63</td>
<td>65</td>
<td>59</td>
<td>65</td>
<td>58.0</td>
<td>fail</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>88</td>
<td>78</td>
<td>71</td>
<td>50</td>
<td>65.0</td>
<td>fail</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>68</td>
<td>66</td>
<td>98</td>
<td>62</td>
<td>84.0</td>
<td>pass</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>63</td>
<td>55</td>
<td>92</td>
<td>45</td>
<td>55.0</td>
<td>fail</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>The dataset:</strong></p>
<p>This is the same 300-student dataset from Weeks 3 and 5: four features (attendance, homework_rate, quiz_avg, exam_avg), a final score computed from a weighted formula with noise, and a pass/fail label. The class distribution is 157 pass and 143 fail. For a full explanation of how this dataset is built, refer to the Week 3 or Week 5 demo.</p>
</section>
<section id="part-2-training-a-classifier" class="level2">
<h2 class="anchored" data-anchor-id="part-2-training-a-classifier">Part 2: Training a Classifier</h2>
<p>Before we can explore uncertainty estimates, we need a trained classifier. This section trains a Logistic Regression model using the same workflow from Week 3.</p>
<div id="49e1ef9f" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare features and target</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df[[<span class="st">"attendance"</span>, <span class="st">"homework_rate"</span>, <span class="st">"quiz_avg"</span>, <span class="st">"exam_avg"</span>]]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">"pass_fail"</span>]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Split into training and test sets</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    X, y, test_size<span class="op">=</span><span class="fl">0.25</span>, random_state<span class="op">=</span><span class="dv">42</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Training set: </span><span class="sc">{</span><span class="bu">len</span>(X_train)<span class="sc">}</span><span class="ss"> students"</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Test set: </span><span class="sc">{</span><span class="bu">len</span>(X_test)<span class="sc">}</span><span class="ss"> students</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Train the model</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>logreg <span class="op">=</span> LogisticRegression(C<span class="op">=</span><span class="fl">1.0</span>, max_iter<span class="op">=</span><span class="dv">1000</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>logreg.fit(X_train, y_train)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate with .score() and .predict()</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Training accuracy: </span><span class="sc">{</span>logreg<span class="sc">.</span>score(X_train, y_train)<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Test accuracy: </span><span class="sc">{</span>logreg<span class="sc">.</span>score(X_test, y_test)<span class="sc">:.3f}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Show predictions for the first 10 test students</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>predictions <span class="op">=</span> logreg.predict(X_test)</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Predictions for first 10 test students:"</span>)</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(predictions[:<span class="dv">10</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training set: 225 students
Test set: 75 students

Training accuracy: 0.880
Test accuracy: 0.867

Predictions for first 10 test students:
['pass' 'fail' 'fail' 'fail' 'pass' 'pass' 'pass' 'fail' 'pass' 'fail']</code></pre>
</div>
</div>
<p><strong>What we have so far:</strong></p>
<p>This is the familiar workflow from Week 3: split the data, create a LogisticRegression model, train it, and evaluate. Training accuracy is 0.880 and test accuracy is 0.867, so the model generalizes well.</p>
<p>The <code>.predict()</code> output for the first 10 test students shows labels: ‘pass’, ‘fail’, ‘fail’, and so on. But look at those predictions. The model says Student 0 will pass and Student 1 will fail. Is it equally confident about both? Is Student 0 a strong pass or a borderline case?</p>
</section>
<section id="part-3-predicted-probabilities-with-predict_proba" class="level2">
<h2 class="anchored" data-anchor-id="part-3-predicted-probabilities-with-predict_proba">Part 3: Predicted Probabilities with <code>predict_proba</code></h2>
<section id="what-predict_proba-is" class="level3">
<h3 class="anchored" data-anchor-id="what-predict_proba-is">What <code>predict_proba</code> Is</h3>
<p><code>predict_proba</code> is a method available on most scikit-learn classifiers (including LogisticRegression, DecisionTreeClassifier, and KNeighborsClassifier) that returns a <strong>probability for each class</strong> instead of a single label. For our binary pass/fail problem, that means each student gets two numbers: the probability the model assigns to “fail” and the probability it assigns to “pass.”</p>
</section>
<section id="what-the-output-looks-like" class="level3">
<h3 class="anchored" data-anchor-id="what-the-output-looks-like">What the Output Looks Like</h3>
<p>When you call <code>predict_proba</code>, you get back an array with <strong>one row per student and one column per class</strong>. For our test set of 75 students with 2 classes, the output is a 75×2 array. The column order matches the <code>classes_</code> attribute of the trained model. In our case, column 0 is P(fail) and column 1 is P(pass).</p>
<p>Each row sums to 1.0, because the model distributes 100% of its belief across the possible classes. If the model is 90% sure a student will pass, there’s only 10% left for fail.</p>
</section>
<section id="how-it-connects-to-.predict" class="level3">
<h3 class="anchored" data-anchor-id="how-it-connects-to-.predict">How It Connects to <code>.predict()</code></h3>
<p>Behind the scenes, <code>.predict()</code> is actually using <code>predict_proba</code>. It gets the probabilities, finds whichever class has the higher probability, and returns that class name. The threshold is 0.5: if P(pass) ≥ 0.5, the prediction is “pass.” This means <code>.predict()</code> is just the last step of a probability calculation, and <code>predict_proba</code> lets you see the full picture before that final step.</p>
</section>
<section id="calling-predict_proba" class="level3">
<h3 class="anchored" data-anchor-id="calling-predict_proba">Calling <code>predict_proba</code></h3>
<div id="e14c9d8f" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get predicted probabilities for test students</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>proba <span class="op">=</span> logreg.predict_proba(X_test)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Shape of predict_proba output: </span><span class="sc">{</span>proba<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Classes (column order): </span><span class="sc">{</span>logreg<span class="sc">.</span>classes_<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Predicted probabilities for first 10 test students:"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.<span class="bu">round</span>(proba[:<span class="dv">10</span>], <span class="dv">3</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Shape of predict_proba output: (75, 2)
Classes (column order): ['fail' 'pass']

Predicted probabilities for first 10 test students:
[[0.489 0.511]
 [0.99  0.01 ]
 [0.926 0.074]
 [0.985 0.015]
 [0.463 0.537]
 [0.001 0.999]
 [0.003 0.997]
 [0.829 0.171]
 [0.137 0.863]
 [0.544 0.456]]</code></pre>
</div>
</div>
<p><strong>Understanding the code:</strong></p>
<p><strong>Calling <code>predict_proba</code>:</strong> - <code>logreg.predict_proba(X_test)</code> calls the method on our trained model, passing in the test features, the same pattern as <code>.predict(X_test)</code> - The result is stored in <code>proba</code>, a 2D NumPy array</p>
<p><strong>Inspecting the output:</strong> - <code>proba.shape</code> confirms the dimensions: (75, 2), meaning 75 test students and 2 columns - <code>logreg.classes_</code> shows the column order: <code>['fail', 'pass']</code>, confirming column 0 is P(fail) and column 1 is P(pass) - <code>np.round(proba[:10], 3)</code> displays the first 10 rows rounded to three decimal places. <code>[:10]</code> selects the first 10 rows, and <code>.round(3)</code> makes the numbers easier to read</p>
<p><strong>Reading the actual output:</strong></p>
<ul>
<li>Student 0: P(fail)=0.489, P(pass)=0.511. The model slightly favors “pass,” but barely above the 0.5 threshold</li>
<li>Student 1: P(fail)=0.990, P(pass)=0.010. The model is very confident this student will fail</li>
<li>Student 5: P(fail)=0.001, P(pass)=0.999. The model is very confident this student will pass</li>
</ul>
<p>The range of confidence across these 10 students is wide, from near-certain (0.990, 0.999) to barely decided (0.511).</p>
</section>
<section id="how-predict_proba-relates-to-.predict" class="level3">
<h3 class="anchored" data-anchor-id="how-predict_proba-relates-to-.predict">How <code>predict_proba</code> Relates to <code>.predict()</code></h3>
<div id="9e7331b7" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Each row sums to 1.0</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Row sums for first 10 students:"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(proba[:<span class="dv">10</span>].<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">1</span>).<span class="bu">round</span>(<span class="dv">3</span>))</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co"># The class with the higher probability IS the prediction</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'Student'</span><span class="sc">:&lt;10}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'P(fail)'</span><span class="sc">:&lt;10}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'P(pass)'</span><span class="sc">:&lt;10}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'predict()'</span><span class="sc">:&lt;12}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'Match?'</span><span class="sc">:&lt;8}</span><span class="ss">"</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"-"</span> <span class="op">*</span> <span class="dv">50</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10</span>):</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    higher_class <span class="op">=</span> <span class="st">"pass"</span> <span class="cf">if</span> proba[i, <span class="dv">1</span>] <span class="op">&gt;=</span> <span class="fl">0.5</span> <span class="cf">else</span> <span class="st">"fail"</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>    match <span class="op">=</span> <span class="st">"✓"</span> <span class="cf">if</span> higher_class <span class="op">==</span> predictions[i] <span class="cf">else</span> <span class="st">"✗"</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>i<span class="sc">:&lt;10}</span><span class="ss"> </span><span class="sc">{</span>proba[i,<span class="dv">0</span>]<span class="sc">:&lt;10.3f}</span><span class="ss"> </span><span class="sc">{</span>proba[i,<span class="dv">1</span>]<span class="sc">:&lt;10.3f}</span><span class="ss"> </span><span class="sc">{</span>predictions[i]<span class="sc">:&lt;12}</span><span class="ss"> </span><span class="sc">{</span>match<span class="sc">:&lt;8}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Row sums for first 10 students:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Student    P(fail)    P(pass)    predict()    Match?  
--------------------------------------------------
0          0.489      0.511      pass         ✓       
1          0.990      0.010      fail         ✓       
2          0.926      0.074      fail         ✓       
3          0.985      0.015      fail         ✓       
4          0.463      0.537      pass         ✓       
5          0.001      0.999      pass         ✓       
6          0.003      0.997      pass         ✓       
7          0.829      0.171      fail         ✓       
8          0.137      0.863      pass         ✓       
9          0.544      0.456      fail         ✓       </code></pre>
</div>
</div>
<p><strong>Understanding the code:</strong></p>
<p><strong>Checking that rows sum to 1.0:</strong> - <code>proba[:10].sum(axis=1)</code> takes the first 10 rows of probabilities and adds across each row - <code>axis=1</code> means “sum across columns” (i.e., add P(fail) + P(pass) for each student) - <code>.round(3)</code> rounds to three decimal places for readability</p>
<p><strong>Building the comparison table:</strong> - The <code>for</code> loop goes through the first 10 students one at a time - For each student, <code>higher_class = "pass" if proba[i, 1] &gt;= 0.5 else "fail"</code> checks which class has the higher probability - <code>match = "✓" if higher_class == predictions[i] else "✗"</code> compares that to the actual <code>.predict()</code> output - The formatted print statement aligns the columns into a readable table</p>
<p><strong>Understanding the output:</strong></p>
<p>The row sums confirm that every student’s probabilities add to exactly 1.0.</p>
<p>The comparison table verifies the relationship between <code>predict_proba</code> and <code>.predict()</code>: every row shows a ✓, confirming that <code>.predict()</code> returns whichever class has the higher probability. Student 0 has P(pass)=0.511 (higher than P(fail)=0.489), so <code>.predict()</code> returns “pass.” Student 1 has P(fail)=0.990 (higher than P(pass)=0.010), so <code>.predict()</code> returns “fail.”</p>
</section>
<section id="examining-individual-students" class="level3">
<h3 class="anchored" data-anchor-id="examining-individual-students">Examining Individual Students</h3>
<div id="83f85ce9" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Build a table combining predictions, probabilities, and actual outcomes</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>results_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"quiz_avg"</span>: X_test[<span class="st">"quiz_avg"</span>].values,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"exam_avg"</span>: X_test[<span class="st">"exam_avg"</span>].values,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"actual"</span>: y_test.values,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"predicted"</span>: predictions,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"P(fail)"</span>: proba[:, <span class="dv">0</span>].<span class="bu">round</span>(<span class="dv">3</span>),</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"P(pass)"</span>: proba[:, <span class="dv">1</span>].<span class="bu">round</span>(<span class="dv">3</span>),</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"correct"</span>: y_test.values <span class="op">==</span> predictions</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Show a selection of students with different confidence levels</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="co"># High confidence correct, low confidence correct, and confident but wrong</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>example_indices <span class="op">=</span> [<span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">8</span>, <span class="dv">0</span>, <span class="dv">9</span>, <span class="dv">7</span>, <span class="dv">4</span>]</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Selected test students (sorted from most confident to least confident):"</span>)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>results_df.iloc[example_indices]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Selected test students (sorted from most confident to least confident):
</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">quiz_avg</th>
<th data-quarto-table-cell-role="th">exam_avg</th>
<th data-quarto-table-cell-role="th">actual</th>
<th data-quarto-table-cell-role="th">predicted</th>
<th data-quarto-table-cell-role="th">P(fail)</th>
<th data-quarto-table-cell-role="th">P(pass)</th>
<th data-quarto-table-cell-role="th">correct</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">5</th>
<td>81</td>
<td>92</td>
<td>pass</td>
<td>pass</td>
<td>0.001</td>
<td>0.999</td>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>90</td>
<td>41</td>
<td>fail</td>
<td>fail</td>
<td>0.990</td>
<td>0.010</td>
<td>True</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>72</td>
<td>83</td>
<td>pass</td>
<td>pass</td>
<td>0.137</td>
<td>0.863</td>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">0</th>
<td>96</td>
<td>49</td>
<td>pass</td>
<td>pass</td>
<td>0.489</td>
<td>0.511</td>
<td>True</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">9</th>
<td>98</td>
<td>49</td>
<td>fail</td>
<td>fail</td>
<td>0.544</td>
<td>0.456</td>
<td>True</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>68</td>
<td>71</td>
<td>pass</td>
<td>fail</td>
<td>0.829</td>
<td>0.171</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>48</td>
<td>86</td>
<td>fail</td>
<td>pass</td>
<td>0.463</td>
<td>0.537</td>
<td>False</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Understanding the code:</strong></p>
<p><strong>Building the results table:</strong> - <code>pd.DataFrame({...})</code> creates a new table from scratch with the columns we want to see together - <code>X_test["quiz_avg"].values</code> extracts quiz averages as a plain array (<code>.values</code> removes the DataFrame index so rows line up cleanly) - <code>proba[:, 0].round(3)</code> takes column 0 (probability of fail) from the probability array and rounds to three decimals - <code>y_test.values == predictions</code> compares actual outcomes to predictions element by element, producing <code>True</code> or <code>False</code> for each student</p>
<p><strong>Selecting specific students:</strong> - <code>example_indices = [5, 1, 8, 0, 9, 7, 4]</code> is a hand-picked list of test set positions chosen to show a range of confidence levels - <code>results_df.iloc[example_indices]</code> selects those specific rows by position. <code>.iloc</code> means “select by integer location”</p>
<p><strong>Understanding the output:</strong></p>
<p>This table includes quiz_avg and exam_avg alongside the probabilities so you can connect the input features to the model’s confidence level.</p>
<p><strong>High confidence, correct predictions:</strong> - Student 5: quiz_avg=81, exam_avg=92, P(pass)=0.999. Both scores are well above average, and the model is nearly certain this student passes - Student 1: quiz_avg=90, exam_avg=41, P(fail)=0.990. Despite a strong quiz average, the very low exam score leads the model to confidently predict fail</p>
<p><strong>Moderate confidence, correct prediction:</strong> - Student 8: quiz_avg=72, exam_avg=83, P(pass)=0.863. Solid scores that lean toward passing, but not overwhelmingly so</p>
<p><strong>Low confidence, correct predictions:</strong> - Student 0: quiz_avg=96, exam_avg=49, P(pass)=0.511. A high quiz average but a low exam average. These mixed signals leave the model barely above the 0.5 threshold - Student 9: quiz_avg=98, exam_avg=49, P(fail)=0.544. Very similar pattern to Student 0, but the balance tips slightly the other way</p>
<p><strong>Confident but wrong:</strong> - Student 7: quiz_avg=68, exam_avg=71, P(fail)=0.829, actual=pass. Both scores are on the lower end, making the model fairly confident this student would fail. But the student actually passed, possibly because of stronger attendance or homework scores (features included in the model but not shown in this table)</p>
<p><strong>Wrong at low confidence:</strong> - Student 4: quiz_avg=48, exam_avg=86, P(pass)=0.537, actual=fail. The high exam score leads the model to narrowly predict “pass,” but the student actually failed. When the model is this uncertain, the prediction is unreliable.</p>
</section>
</section>
<section id="part-4-the-decision-function" class="level2">
<h2 class="anchored" data-anchor-id="part-4-the-decision-function">Part 4: The Decision Function</h2>
<section id="understanding-decision_function" class="level3">
<h3 class="anchored" data-anchor-id="understanding-decision_function">Understanding <code>decision_function</code></h3>
<p><code>predict_proba</code> gives us probabilities — values between 0 and 1 with a clear interpretation. Scikit-learn provides a second method for measuring prediction confidence called <code>decision_function</code>, which works differently.</p>
<p>Instead of returning probabilities for each class, <code>decision_function</code> returns a single raw score per student. This score is not bounded between 0 and 1. It can be any number, positive or negative.</p>
<p>The score works like this:</p>
<ul>
<li><strong>Positive values</strong> mean the model leans toward one class (“pass” in our case)</li>
<li><strong>Negative values</strong> mean the model leans toward the other class (“fail”)</li>
<li><strong>Values near zero</strong> mean the model is uncertain and it could go either way</li>
<li><strong>Large absolute values</strong> (far from zero in either direction) mean the model is confident</li>
</ul>
<p>Scikit-learn refers to these two sides as the “positive class” and the “negative class.” The positive class is always the second entry in <code>classes_</code>, and the negative class is the first. In our model, <code>logreg.classes_</code> is <code>['fail', 'pass']</code>, so “fail” is the negative class and “pass” is the positive class. That is why positive decision_function values point toward “pass” and negative values point toward “fail.”</p>
<p>The connection to <code>.predict()</code> is the sign: if the decision function is positive, <code>.predict()</code> returns the positive class (“pass”); if negative, it returns the negative class (“fail”). The threshold is 0 rather than 0.5.</p>
<p><strong>Why learn <code>decision_function</code> when <code>predict_proba</code> exists?</strong> Not all classifiers support <code>predict_proba</code>. For example, LinearSVC (a linear classifier from the textbook) only provides <code>decision_function</code>. When <code>predict_proba</code> is available, it’s generally easier to interpret, but <code>decision_function</code> is the more universally available method.</p>
<div id="73262531" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get decision function values for test students</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>dec_func <span class="op">=</span> logreg.decision_function(X_test)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Shape of decision_function output: </span><span class="sc">{</span>dec_func<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">First 10 values:"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.<span class="bu">round</span>(dec_func[:<span class="dv">10</span>], <span class="dv">3</span>))</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Minimum value: </span><span class="sc">{</span>dec_func<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Maximum value: </span><span class="sc">{</span>dec_func<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Shape of decision_function output: (75,)

First 10 values:
[ 0.046 -4.553 -2.533 -4.203  0.149  7.206  5.78  -1.577  1.837 -0.177]

Minimum value: -7.038
Maximum value: 8.530</code></pre>
</div>
</div>
<p><strong>Understanding the code:</strong></p>
<p><strong>Calling <code>decision_function</code>:</strong> - <code>logreg.decision_function(X_test)</code> calls the method on our trained model, passing in test features, the same pattern as <code>predict_proba</code> and <code>.predict()</code> - The result is stored in <code>dec_func</code>, a 1D NumPy array (one value per student, not two columns)</p>
<p><strong>Inspecting the output:</strong> - <code>dec_func.shape</code> confirms the output is (75,), a flat array with one score per test student - <code>np.round(dec_func[:10], 3)</code> displays the first 10 values rounded to three decimals - <code>dec_func.min()</code> and <code>dec_func.max()</code> show the full range of scores in our data</p>
<p><strong>Why one value instead of two?</strong> With <code>predict_proba</code>, we got two columns (P(fail) and P(pass)), but those two columns are redundant because they always sum to 1.0. If you know P(pass) is 0.863, you automatically know P(fail) is 0.137. <code>decision_function</code> skips that redundancy entirely. A single number encodes everything: the sign tells you which class the model favors (positive = “pass,” negative = “fail”), and the magnitude tells you how confident the model is (farther from zero = more confident). This is specific to binary classification — the textbook shows that with three or more classes, <code>decision_function</code> returns one score per class, similar to how <code>predict_proba</code> works.</p>
<p><strong>Reading the actual output:</strong></p>
<ul>
<li>Student 0: 0.046, barely positive, matching the near-50/50 split we saw in <code>predict_proba</code> (P(pass)=0.511)</li>
<li>Student 5: 7.206, strongly positive, matching the near-certain P(pass)=0.999</li>
</ul>
<p>The range from -7.038 to 8.530 shows why these values are harder to interpret than probabilities — there’s no natural scale. A score of 7.2 is very confident, but you can’t say “that means 99% confident” without converting it to a probability first. The range depends on the specific model and data, so these values only make sense relative to each other within this model. You cannot compare decision_function scores across different models or datasets.</p>
</section>
<section id="comparing-predict_proba-and-decision_function" class="level3">
<h3 class="anchored" data-anchor-id="comparing-predict_proba-and-decision_function">Comparing <code>predict_proba</code> and <code>decision_function</code></h3>
<div id="9e84a683" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Side-by-side comparison for the first 10 students</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>comparison <span class="op">=</span> pd.DataFrame({</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"decision_function"</span>: np.<span class="bu">round</span>(dec_func[:<span class="dv">10</span>], <span class="dv">3</span>),</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"P(fail)"</span>: np.<span class="bu">round</span>(proba[:<span class="dv">10</span>, <span class="dv">0</span>], <span class="dv">3</span>),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"P(pass)"</span>: np.<span class="bu">round</span>(proba[:<span class="dv">10</span>, <span class="dv">1</span>], <span class="dv">3</span>),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"predicted"</span>: predictions[:<span class="dv">10</span>],</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"actual"</span>: y_test.values[:<span class="dv">10</span>]</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>comparison</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">decision_function</th>
<th data-quarto-table-cell-role="th">P(fail)</th>
<th data-quarto-table-cell-role="th">P(pass)</th>
<th data-quarto-table-cell-role="th">predicted</th>
<th data-quarto-table-cell-role="th">actual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0.046</td>
<td>0.489</td>
<td>0.511</td>
<td>pass</td>
<td>pass</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>-4.553</td>
<td>0.990</td>
<td>0.010</td>
<td>fail</td>
<td>fail</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>-2.533</td>
<td>0.926</td>
<td>0.074</td>
<td>fail</td>
<td>fail</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>-4.203</td>
<td>0.985</td>
<td>0.015</td>
<td>fail</td>
<td>fail</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>0.149</td>
<td>0.463</td>
<td>0.537</td>
<td>pass</td>
<td>fail</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>7.206</td>
<td>0.001</td>
<td>0.999</td>
<td>pass</td>
<td>pass</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>5.780</td>
<td>0.003</td>
<td>0.997</td>
<td>pass</td>
<td>pass</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>-1.577</td>
<td>0.829</td>
<td>0.171</td>
<td>fail</td>
<td>pass</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>1.837</td>
<td>0.137</td>
<td>0.863</td>
<td>pass</td>
<td>pass</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>-0.177</td>
<td>0.544</td>
<td>0.456</td>
<td>fail</td>
<td>fail</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Understanding the code:</strong></p>
<p><strong>Building the side-by-side table:</strong> - <code>pd.DataFrame({...})</code> creates a table with five columns so we can compare both methods for the same students - <code>np.round(dec_func[:10], 3)</code> takes the first 10 decision function values and rounds to three decimals - <code>np.round(proba[:10, 0], 3)</code> takes the first 10 rows of column 0 (P(fail)) from the probability array - <code>predictions[:10]</code> and <code>y_test.values[:10]</code> pull the first 10 predictions and actual outcomes</p>
<p><strong>Understanding the output:</strong></p>
<p>The table confirms both methods agree on every prediction: when decision_function is positive, P(pass) &gt; 0.5, and vice versa. Higher absolute decision_function values correspond to more extreme probabilities. The difference is how they express confidence:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 36%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th><code>predict_proba</code></th>
<th><code>decision_function</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Output shape (binary)</td>
<td>2 columns (one per class)</td>
<td>1 column</td>
</tr>
<tr class="even">
<td>Value range</td>
<td>0 to 1</td>
<td>Arbitrary (no fixed bounds)</td>
</tr>
<tr class="odd">
<td>Interpretation</td>
<td>Direct probability (“83% likely to pass”)</td>
<td>Relative score (larger = more confident)</td>
</tr>
<tr class="even">
<td>Row sums</td>
<td>Always sum to 1.0</td>
<td>Not applicable</td>
</tr>
<tr class="odd">
<td>Threshold</td>
<td>0.5</td>
<td>0</td>
</tr>
</tbody>
</table>
<p><strong>Which should you use?</strong> When both are available, <code>predict_proba</code> is generally the better choice because probabilities have a natural interpretation. “The model thinks there’s an 83% chance this student passes” is more meaningful than “the decision function score is 1.837.”</p>
</section>
</section>
<section id="part-5-why-confidence-matters" class="level2">
<h2 class="anchored" data-anchor-id="part-5-why-confidence-matters">Part 5: Why Confidence Matters</h2>
<p>The previous sections showed how to get confidence scores. This section shows why that information is practically useful.</p>
<section id="a-note-on-boolean-indexing-in-numpy" class="level3">
<h3 class="anchored" data-anchor-id="a-note-on-boolean-indexing-in-numpy">A Note on Boolean Indexing in NumPy</h3>
<p>The code in this section uses a technique called <strong>boolean indexing</strong> to select specific elements from NumPy arrays. If you haven’t seen this before, this explanation will walk you through how it works. Every operation in the code below builds on these basics.</p>
<p><strong>Creating a boolean array from a comparison</strong></p>
<p>When you compare a NumPy array to a value, the result is a new array of <code>True</code> and <code>False</code> values, one for each element. For example, suppose we have an array of four confidence values:</p>
<pre><code>confidences = np.array([0.955, 0.623, 0.999, 0.511])
confidences &gt; 0.9</code></pre>
<p>This produces <code>[True, False, True, False]</code>. The comparison is applied to each element individually: 0.955 &gt; 0.9 is True, 0.623 &gt; 0.9 is False, and so on. The result is always the same length as the original array.</p>
<p><strong>Using a boolean array to select elements</strong></p>
<p>You can pass a boolean array inside square brackets to select only the elements where the value is <code>True</code>. Using the example above:</p>
<pre><code>high_conf = confidences &gt; 0.9
confidences[high_conf]</code></pre>
<p>This returns <code>[0.955, 0.999]</code>, the two values where high_conf is True. The boolean array acts as a filter: True means “keep this element,” False means “skip it.” This works across arrays of the same length, so if you have a separate predictions array, <code>predictions[high_conf]</code> would return the predictions for those same positions.</p>
<p><strong>Combining multiple conditions with <code>&amp;</code></strong></p>
<p>You can combine two conditions using <code>&amp;</code> (and). Each element must satisfy both conditions to be True:</p>
<pre><code>moderate = (confidences &gt; 0.7) &amp; (confidences &lt;= 0.9)</code></pre>
<p>This produces <code>[False, False, False, False]</code> for our example (none of the four values fall between 0.7 and 0.9). The parentheses around each condition are required because of how Python handles operator precedence. Without them, the expression would produce an error.</p>
<p><strong>Flipping with <code>~</code> (not)</strong></p>
<p>The <code>~</code> operator flips every True to False and every False to True:</p>
<pre><code>correct = np.array([True, True, False, True])
~correct</code></pre>
<p>This produces <code>[False, False, True, False]</code>. This is useful when you want the opposite selection. If <code>correct</code> marks which predictions were right, then <code>~correct</code> marks which predictions were wrong.</p>
<p><strong>Counting and averaging boolean arrays</strong></p>
<p>Python treats True as 1 and False as 0, which means you can use math operations on boolean arrays:</p>
<pre><code>np.sum(high_conf)</code></pre>
<p>Returns 2, the number of True values. This tells you how many elements passed the filter.</p>
<pre><code>np.mean(confidences[high_conf] &gt; 0.95)</code></pre>
<p>Returns the fraction of the selected elements that satisfy the condition. If one out of two is above 0.95, the mean is 0.5. The code below uses <code>np.mean(predictions[mask] == actual[mask])</code> to calculate accuracy within a group: it compares predictions to actual outcomes for just the filtered students, then takes the mean of the resulting True/False array to get the fraction correct.</p>
<div id="3b00fa68" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group test students by confidence level</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>max_proba <span class="op">=</span> np.<span class="bu">max</span>(proba, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>actual <span class="op">=</span> y_test.values</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Define confidence tiers</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>very_confident <span class="op">=</span> max_proba <span class="op">&gt;</span> <span class="fl">0.9</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>moderate <span class="op">=</span> (max_proba <span class="op">&gt;</span> <span class="fl">0.7</span>) <span class="op">&amp;</span> (max_proba <span class="op">&lt;=</span> <span class="fl">0.9</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>uncertain <span class="op">=</span> (max_proba <span class="op">&gt;</span> <span class="fl">0.5</span>) <span class="op">&amp;</span> (max_proba <span class="op">&lt;=</span> <span class="fl">0.7</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate accuracy within each tier</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>acc_vc <span class="op">=</span> np.mean(predictions[very_confident] <span class="op">==</span> actual[very_confident])</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>acc_mod <span class="op">=</span> np.mean(predictions[moderate] <span class="op">==</span> actual[moderate])</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>acc_unc <span class="op">=</span> np.mean(predictions[uncertain] <span class="op">==</span> actual[uncertain])</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy by confidence level:"</span>)</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Very confident (&gt;90%):       </span><span class="sc">{</span>acc_vc<span class="sc">:.3f}</span><span class="ss"> accuracy (</span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">sum</span>(very_confident)<span class="sc">}</span><span class="ss"> students)"</span>)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Moderately confident (70-90%): </span><span class="sc">{</span>acc_mod<span class="sc">:.3f}</span><span class="ss"> accuracy (</span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">sum</span>(moderate)<span class="sc">}</span><span class="ss"> students)"</span>)</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  Uncertain (50-70%):          </span><span class="sc">{</span>acc_unc<span class="sc">:.3f}</span><span class="ss"> accuracy (</span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">sum</span>(uncertain)<span class="sc">}</span><span class="ss"> students)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy by confidence level:
  Very confident (&gt;90%):       0.955 accuracy (44 students)
  Moderately confident (70-90%): 0.833 accuracy (18 students)
  Uncertain (50-70%):          0.615 accuracy (13 students)</code></pre>
</div>
</div>
<p><strong>Understanding the code:</strong></p>
<p><strong>Calculating each student’s confidence:</strong> - <code>np.max(proba, axis=1)</code> takes the higher of the two probabilities for each student. This is the model’s confidence in its prediction, regardless of which class it predicted - <code>axis=1</code> means “find the max across columns” (comparing P(fail) vs P(pass) for each row) - For example, if P(fail)=0.829 and P(pass)=0.171, the max is 0.829, so the model is 82.9% confident</p>
<p><strong>Creating confidence tiers with boolean masks:</strong> - <code>very_confident = max_proba &gt; 0.9</code> creates an array of <code>True</code>/<code>False</code> values, where <code>True</code> marks students whose confidence exceeds 90% - <code>moderate = (max_proba &gt; 0.7) &amp; (max_proba &lt;= 0.9)</code> uses <code>&amp;</code> to combine two conditions (confidence between 70% and 90%) - <code>uncertain = (max_proba &gt; 0.5) &amp; (max_proba &lt;= 0.7)</code> captures students where confidence is between 50% and 70% - These boolean arrays act as filters: <code>predictions[very_confident]</code> selects only the predictions for students in the very confident group</p>
<p><strong>Calculating accuracy within each tier:</strong> - <code>predictions[very_confident] == actual[very_confident]</code> compares predictions to actual outcomes, but only for students in that confidence tier - <code>np.mean(...)</code> converts the <code>True</code>/<code>False</code> comparisons into a fraction. <code>True</code> counts as 1, <code>False</code> as 0, so the mean is the accuracy - <code>np.sum(very_confident)</code> counts how many students fall in each tier</p>
<p><strong>Understanding the output:</strong></p>
<p>This analysis groups students by how confident the model was in its prediction, then checks how accurate those predictions actually were:</p>
<ul>
<li><strong>Very confident (&gt;90%):</strong> The model was correct 95.5% of the time across 44 students. When the model is highly confident, it’s almost always right.</li>
<li><strong>Moderately confident (70-90%):</strong> Accuracy drops to 83.3% across 18 students. Still useful, but more mistakes.</li>
<li><strong>Uncertain (50-70%):</strong> Accuracy drops to 61.5% across 13 students. When the model is uncertain, it’s barely better than guessing.</li>
</ul>
<p>This pattern is important: <strong>the model’s confidence is informative.</strong> Higher confidence predictions tend to be more accurate. This means you can use <code>predict_proba</code> not just to get a prediction, but to decide how much to trust that prediction.</p>
<p>What we just did — checking whether the model’s reported confidence matches its actual accuracy — is closely related to a concept the textbook calls <strong>calibration</strong>. A model is calibrated if predictions made with 90% confidence are actually correct about 90% of the time, predictions made with 70% confidence are correct about 70% of the time, and so on. Our very confident tier (&gt;90%) had 95.5% accuracy, which is reasonably close to the reported confidence. Not all models are this well-behaved. Some are systematically overconfident (reporting high probabilities but being wrong more often than expected) or underconfident (being correct more often than the probabilities suggest). The textbook discusses calibration in more detail in the Uncertainty Estimates section.</p>
<div id="08086f37" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the distribution of prediction confidence</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Separate correct and incorrect predictions</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>correct_mask <span class="op">=</span> predictions <span class="op">==</span> actual</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>ax.hist(max_proba[correct_mask], bins<span class="op">=</span><span class="dv">10</span>, <span class="bu">range</span><span class="op">=</span>(<span class="fl">0.5</span>, <span class="fl">1.0</span>), </span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>        alpha<span class="op">=</span><span class="fl">0.7</span>, label<span class="op">=</span><span class="st">"Correct predictions"</span>, color<span class="op">=</span><span class="st">"steelblue"</span>)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>ax.hist(max_proba[<span class="op">~</span>correct_mask], bins<span class="op">=</span><span class="dv">10</span>, <span class="bu">range</span><span class="op">=</span>(<span class="fl">0.5</span>, <span class="fl">1.0</span>), </span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>        alpha<span class="op">=</span><span class="fl">0.7</span>, label<span class="op">=</span><span class="st">"Incorrect predictions"</span>, color<span class="op">=</span><span class="st">"salmon"</span>)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Prediction Confidence (max probability)"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Number of Students"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Distribution of Prediction Confidence"</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>ax.legend(fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="week-7-demo_files/figure-html/cell-10-output-1.png" width="951" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Understanding the code:</strong></p>
<p><strong>Setting up the plot:</strong> - <code>fig, ax = plt.subplots(figsize=(10, 6))</code> creates a figure that is 10 inches wide and 6 inches tall - <code>correct_mask = predictions == actual</code> creates a boolean array. <code>True</code> marks students the model got right, <code>False</code> marks students it got wrong</p>
<p><strong>Drawing the histograms:</strong> - <code>ax.hist(max_proba[correct_mask], ...)</code> draws a histogram using only the confidence values for correctly predicted students - <code>ax.hist(max_proba[~correct_mask], ...)</code> draws a second histogram for incorrectly predicted students. The <code>~</code> operator flips <code>True</code> to <code>False</code> and vice versa - <code>bins=10</code> divides the confidence range into 10 equal intervals - <code>range=(0.5, 1.0)</code> limits the x-axis to 0.5–1.0 (since the minimum possible confidence is 0.5, because whichever class the model picks must be above 50%) - <code>alpha=0.7</code> makes the bars slightly transparent so overlapping bars are visible</p>
<p><strong>Interpreting the plot:</strong></p>
<p>This histogram shows how prediction confidence is distributed across all 75 test students, with correct predictions in blue and incorrect predictions in salmon.</p>
<p>The pattern reinforces what the accuracy table showed: most of the high-confidence predictions (right side of the plot) are correct, while the incorrect predictions tend to cluster at lower confidence levels (left side). The model’s mistakes are concentrated in the uncertain zone.</p>
<p><strong>Practical implication:</strong> If you’re building a system that acts on predictions, you could set a confidence threshold. For example, you might only flag students for intervention when P(fail) &gt; 0.8, knowing that highly confident predictions are much more reliable. Students in the uncertain range (50-70%) might be flagged for review rather than automatic action.</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<section id="key-takeaways" class="level3">
<h3 class="anchored" data-anchor-id="key-takeaways">Key Takeaways</h3>
<ol type="1">
<li><code>.predict()</code> returns only the model’s final label. It hides how confident the model is in that answer</li>
<li><code>predict_proba</code> returns probability estimates for each class, with values between 0 and 1 that sum to 1.0 across classes</li>
<li><code>decision_function</code> returns raw confidence scores on an arbitrary scale, where positive means one class and negative means the other</li>
<li><code>.predict()</code> is equivalent to taking the class with the highest <code>predict_proba</code> value (or the sign of <code>decision_function</code>)</li>
<li>Higher confidence predictions tend to be more accurate, and the model’s uncertainty is informative</li>
<li><code>predict_proba</code> is generally easier to interpret than <code>decision_function</code> because probabilities have a natural meaning</li>
</ol>
</section>
<section id="further-reading-in-the-textbook" class="level3">
<h3 class="anchored" data-anchor-id="further-reading-in-the-textbook">Further Reading in the Textbook</h3>
<p>As you read the Uncertainty Estimates section (pages 119-128), pay attention to:</p>
<ol type="1">
<li><strong>GradientBoostingClassifier examples</strong>
<ul>
<li>The textbook demonstrates both methods on GradientBoostingClassifier with a 2D dataset</li>
<li>The 2D examples allow visualizing decision boundaries and confidence as color maps</li>
</ul></li>
<li><strong>Multiclass uncertainty</strong>
<ul>
<li>In our demo, we used binary classification (two classes)</li>
<li>The textbook shows how <code>predict_proba</code> and <code>decision_function</code> extend to three or more classes</li>
<li>With multiple classes, <code>predict_proba</code> returns one column per class and <code>decision_function</code> returns one score per class</li>
<li>The <code>classes_</code> attribute maps column indices to actual class names</li>
</ul></li>
<li><strong>Calibration</strong>
<ul>
<li>Our confidence tier analysis in Part 5 was an informal version of checking calibration. The textbook discusses this concept in more depth, including how different models vary in how well-calibrated they are</li>
</ul></li>
<li><strong>Summary and Outlook (Chapter 2 wrap-up)</strong>
<ul>
<li>The textbook closes Chapter 2 with a summary comparing all supervised learning algorithms</li>
<li>This includes guidance on when to use each model type: nearest neighbors, linear models, decision trees, random forests, gradient boosting, SVMs, and neural networks</li>
</ul></li>
</ol>
<p>The demo provided the practical foundation: how to extract and interpret uncertainty from classifiers you already know. The textbook provides the complete picture: additional classifiers, multiclass extensions, calibration, and the full Chapter 2 summary.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/SCTCC-Computer-Programming\.github\.io\/cmsc-2208\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function() {
    var elements = document.querySelectorAll('[aria-label]');
    for (var i = 0; i < elements.length; i++) {
      var ariaLabel = elements[i].getAttribute('aria-label');
      elements[i].setAttribute('data-bs-title', ariaLabel);
      elements[i].setAttribute('data-bs-toggle', 'tooltip');
      elements[i].setAttribute('data-bs-placement', 'bottom');
    }
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
  });
</script>




</body></html>