<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>week-5-demo – CMSC 2208 : Introduction to Machine Learning</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-b758ccaa5987ceb1b75504551e579abf.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-b337f537912f5ab074b938eebad4c5d7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-feb0c0ed7aac57d66ec8dce0f6a48183.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-b337f537912f5ab074b938eebad4c5d7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../shared/assets/course.css">
<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed fullcontent quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">CMSC 2208 : Introduction to Machine Learning</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Week 5 Demo: Introduction to Decision Trees</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
        <div class="sidebar-tools-collapse">
    <a href="https://discord.gg/az8cmeqJdc" title="" class="quarto-navigation-tool px-1" aria-label="Discord"><i class="bi bi-chat-dots"></i></a>
    <a href="https://sctcc.learn.minnstate.edu/d2l/login" title="" class="quarto-navigation-tool px-1" aria-label="D2L"><i class="bi bi-book-half"></i></a>
</div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Course information</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course/syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../course/schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/policies/office-hours.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Office Hours</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/policies/homework-coursework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assignment Policies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/policies/general-policies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">General Policies</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/policies/ai-policy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AI Policy</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Weekly Overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weekly-overview/week-03/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weekly-overview/week-04/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../weekly-overview/week-05/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 5 (Starts - 09 FEB)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Weekly Assignments</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../assignments/week-03/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../assignments/week-04/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../assignments/week-05/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 5 (Starts - 09 FEB)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Guides</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 1</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/guides/setup/miniconda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Miniconda Setup</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/guides/setup/jupyter-learning-links.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Jupyter Learning Links</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 2</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/guides/cmsc-2208/week-02/cmsc-2208-chap-02-learning-resources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2 Week 2 Reference Videos</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Week 3</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../shared/guides/cmsc-2208/week-03/cmsc-2208-chap-02-learining-resources-week-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Chapter 2 Week 3 Reference Videos</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 5 Demo: Introduction to Decision Trees</h1>
</div>



<div class="quarto-title-meta">

    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">February 5, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>So far in this course, we’ve explored three different approaches to supervised learning:</p>
<p><strong>Week 2 - k-Nearest Neighbors (kNN):</strong> - <strong>Stores</strong> all training data and searches through it at prediction time - Makes predictions by finding similar examples and voting (or averaging) - Controlled by k: how many neighbors to consider</p>
<p><strong>Week 3 - Linear Models (Ridge Regression, Logistic Regression):</strong> - <strong>Learns a formula</strong> during training: a weighted combination of features - Makes predictions by plugging values into the formula - Controlled by alpha or C: how much regularization to apply</p>
<p><strong>This Week - Decision Trees:</strong> - <strong>Learns a hierarchy of questions</strong> during training (a tree structure) - Makes predictions by asking those questions in order and following branches - Controlled by max_depth: how many questions can be asked in sequence</p>
<section id="what-are-decision-trees" class="level3">
<h3 class="anchored" data-anchor-id="what-are-decision-trees">What Are Decision Trees?</h3>
<p>Decision trees work like the game 20 Questions. When trying to identify something (an animal, object, or person), you ask yes/no questions where each answer leads to another question, until you reach a final decision:</p>
<ul>
<li>“Does it have feathers?” → Yes → “Can it fly?” → No → Penguin!</li>
<li>“Does it have feathers?” → No → “Does it live in water?” → Yes → Dolphin!</li>
</ul>
<p>A decision tree follows this same pattern. It asks a series of questions about the features, and each answer leads to another question, until finally reaching a prediction.</p>
<p><strong>Key characteristics:</strong> - The model is a <strong>tree structure</strong> with questions at each node - Each question splits the data based on one feature - The tree keeps asking questions until it reaches a <strong>leaf</strong> (final decision) - During training, the algorithm figures out <strong>which questions to ask</strong> and <strong>in what order</strong></p>
</section>
<section id="what-makes-decision-trees-different" class="level3">
<h3 class="anchored" data-anchor-id="what-makes-decision-trees-different">What Makes Decision Trees Different?</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 11%">
<col style="width: 34%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>kNN</th>
<th>Linear Models</th>
<th>Decision Trees</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>What it learns</td>
<td>Nothing (stores data)</td>
<td>A formula with weights</td>
<td>A hierarchy of questions</td>
</tr>
<tr class="even">
<td>Training process</td>
<td>Just stores data</td>
<td>Finds optimal weights</td>
<td>Builds tree by asking questions</td>
</tr>
<tr class="odd">
<td>How it predicts</td>
<td>Searches for neighbors</td>
<td>Applies formula</td>
<td>Follows tree branches</td>
</tr>
<tr class="even">
<td>Interpretability</td>
<td>Hard to explain why</td>
<td>Can see feature weights</td>
<td>Can visualize decision path</td>
</tr>
<tr class="odd">
<td>Data requirements</td>
<td>Needs scaling</td>
<td>Needs scaling</td>
<td><strong>No scaling needed!</strong></td>
</tr>
</tbody>
</table>
<p>One of the biggest advantages of decision trees: <strong>you don’t need to scale or normalize your data</strong>. Since each question only looks at one feature at a time (“Is attendance &gt; 80%?”), the scale of other features doesn’t matter.</p>
</section>
<section id="what-this-demo-covers" class="level3">
<h3 class="anchored" data-anchor-id="what-this-demo-covers">What This Demo Covers</h3>
<p>This demo covers: - Building and training a decision tree classifier - Understanding how the <code>max_depth</code> parameter controls tree complexity - Interpreting feature importance to see what the tree learned - Comparing decision trees to the other algorithms we’ve learned - Knowing when to use decision trees vs other approaches</p>
<p>The textbook then shows you: - How to visualize the actual tree structure (with graphviz) - More parameters for controlling tree complexity - Why trees can overfit on complex data - <strong>Ensemble methods</strong> (Random Forests and Gradient Boosting) that combine many trees to make even more powerful models</p>
</section>
</section>
<section id="part-1-creating-the-dataset" class="level2">
<h2 class="anchored" data-anchor-id="part-1-creating-the-dataset">Part 1: Creating the Dataset</h2>
<p>This section continues using the student performance dataset from previous weeks. Using the same dataset helps focus on understanding the new algorithm without having to learn a new domain.</p>
<p>The dataset contains 300 students, each with four features: attendance percentage, homework completion rate, quiz average, and exam average. The target predicts whether each student passes or fails the course.</p>
<div id="a560a759" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create reproducible random data</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">42</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">300</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"attendance"</span>: rng.integers(<span class="dv">60</span>, <span class="dv">101</span>, n),</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"homework_rate"</span>: rng.integers(<span class="dv">50</span>, <span class="dv">101</span>, n),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"quiz_avg"</span>: rng.integers(<span class="dv">40</span>, <span class="dv">101</span>, n),</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"exam_avg"</span>: rng.integers(<span class="dv">40</span>, <span class="dv">101</span>, n),</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Create final score with a realistic formula plus noise</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>base_score <span class="op">=</span> (<span class="fl">0.2</span><span class="op">*</span>df[<span class="st">"homework_rate"</span>] <span class="op">+</span> <span class="fl">0.3</span><span class="op">*</span>df[<span class="st">"quiz_avg"</span>] <span class="op">+</span> <span class="fl">0.5</span><span class="op">*</span>df[<span class="st">"exam_avg"</span>])</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>noise <span class="op">=</span> rng.normal(<span class="dv">0</span>, <span class="dv">5</span>, n)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"final_score"</span>] <span class="op">=</span> (base_score <span class="op">+</span> noise).<span class="bu">round</span>(<span class="dv">0</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Create pass/fail classification target</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"pass_fail"</span>] <span class="op">=</span> np.where(df[<span class="st">"final_score"</span>] <span class="op">&gt;=</span> <span class="dv">70</span>, <span class="st">"pass"</span>, <span class="st">"fail"</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Dataset size: </span><span class="sc">{</span><span class="bu">len</span>(df)<span class="sc">}</span><span class="ss"> students"</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Features: attendance, homework_rate, quiz_avg, exam_avg"</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Target: pass_fail (pass if final_score &gt;= 70, otherwise fail)</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Class distribution:"</span>)</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">"pass_fail"</span>].value_counts())</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>df.head(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Dataset size: 300 students
Features: attendance, homework_rate, quiz_avg, exam_avg
Target: pass_fail (pass if final_score &gt;= 70, otherwise fail)

Class distribution:
pass_fail
pass    157
fail    143
Name: count, dtype: int64
</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="1">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">attendance</th>
<th data-quarto-table-cell-role="th">homework_rate</th>
<th data-quarto-table-cell-role="th">quiz_avg</th>
<th data-quarto-table-cell-role="th">exam_avg</th>
<th data-quarto-table-cell-role="th">final_score</th>
<th data-quarto-table-cell-role="th">pass_fail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>63</td>
<td>68</td>
<td>77</td>
<td>40</td>
<td>63.0</td>
<td>fail</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>91</td>
<td>92</td>
<td>87</td>
<td>42</td>
<td>64.0</td>
<td>fail</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>86</td>
<td>50</td>
<td>85</td>
<td>53</td>
<td>64.0</td>
<td>fail</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>77</td>
<td>95</td>
<td>48</td>
<td>93</td>
<td>68.0</td>
<td>fail</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>77</td>
<td>77</td>
<td>90</td>
<td>67</td>
<td>70.0</td>
<td>pass</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>95</td>
<td>57</td>
<td>72</td>
<td>83</td>
<td>73.0</td>
<td>pass</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>63</td>
<td>65</td>
<td>59</td>
<td>65</td>
<td>58.0</td>
<td>fail</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>88</td>
<td>78</td>
<td>71</td>
<td>50</td>
<td>65.0</td>
<td>fail</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>68</td>
<td>66</td>
<td>98</td>
<td>62</td>
<td>84.0</td>
<td>pass</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>63</td>
<td>55</td>
<td>92</td>
<td>45</td>
<td>55.0</td>
<td>fail</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p><strong>Understanding the code:</strong></p>
<p><strong>Importing libraries:</strong> - <code>numpy</code> (abbreviated as <code>np</code>) provides tools for generating random numbers and doing numerical operations - <code>pandas</code> (abbreviated as <code>pd</code>) lets us work with tables of data called DataFrames - <code>matplotlib.pyplot</code> (abbreviated as <code>plt</code>) is for creating visualizations - <code>train_test_split</code> from scikit-learn will help us split data into training and test sets</p>
<p><strong>Creating reproducible random data:</strong> - <code>rng = np.random.default_rng(42)</code> creates a random number generator with a fixed seed (42). Using a seed means we get the same “random” numbers every time we run this code, making results reproducible. - <code>n = 300</code> sets our dataset size to 300 students</p>
<p><strong>Building the DataFrame:</strong> - <code>pd.DataFrame({...})</code> creates a table with four columns - <code>rng.integers(60, 101, n)</code> generates 300 random whole numbers between 60 and 100 (inclusive) - Each column represents one feature: attendance percentage, homework completion rate, quiz average, and exam average - After this step, we have a table where each row is one student and each column is one measurement</p>
<p><strong>Creating a realistic final score:</strong> - <code>base_score = (0.2*df["homework_rate"] + 0.3*df["quiz_avg"] + 0.5*df["exam_avg"])</code> calculates a weighted average where exams count for 50%, quizzes for 30%, and homework for 20%. Notice attendance isn’t used in the formula. - <code>noise = rng.normal(0, 5, n)</code> generates random variation from a bell curve centered at 0 with a spread of 5 points. This represents unpredictable factors we can’t measure: maybe a student had a headache during the exam, or got lucky on multiple choice questions, or studied extra hard one week. - <code>df["final_score"] = (base_score + noise).round(0)</code> adds the random variation to the base score and rounds to whole numbers</p>
<p><strong>Creating the classification target:</strong> - <code>df["pass_fail"] = np.where(df["final_score"] &gt;= 70, "pass", "fail")</code> creates a binary label where students with final_score ≥ 70 are marked as “pass”, otherwise “fail” - This is our target variable: what the model will learn to predict</p>
<p><strong>Understanding the data:</strong></p>
<p>Each row represents one student. The features tell us about their performance throughout the semester: - <strong>attendance</strong>: What percentage of classes they attended (60-100%) - <strong>homework_rate</strong>: What percentage of homework they completed (50-100%) - <strong>quiz_avg</strong>: Their average quiz score (40-100) - <strong>exam_avg</strong>: Their average exam score (40-100)</p>
<p>The target variable <strong>pass_fail</strong> tells us the outcome: - <strong>“pass”</strong> if their final score was 70 or above - <strong>“fail”</strong> if their final score was below 70</p>
<p>The goal: Build a decision tree that learns to predict pass/fail based on these four features.</p>
</section>
<section id="part-2-building-your-first-decision-tree" class="level2">
<h2 class="anchored" data-anchor-id="part-2-building-your-first-decision-tree">Part 2: Building Your First Decision Tree</h2>
<p>This section builds a decision tree classifier following the same workflow from previous weeks: 1. Split data into training and test sets 2. Create the model 3. Train it on training data 4. Evaluate it on both training and test data</p>
<section id="step-1-prepare-the-data" class="level3">
<h3 class="anchored" data-anchor-id="step-1-prepare-the-data">Step 1: Prepare the data</h3>
<div id="c9ceb665" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select features (X) and target (y)</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df[[<span class="st">"attendance"</span>, <span class="st">"homework_rate"</span>, <span class="st">"quiz_avg"</span>, <span class="st">"exam_avg"</span>]]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">"pass_fail"</span>]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Split into training and test sets (75% train, 25% test)</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    X, y, test_size<span class="op">=</span><span class="fl">0.25</span>, random_state<span class="op">=</span><span class="dv">42</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Training set size: </span><span class="sc">{</span><span class="bu">len</span>(X_train)<span class="sc">}</span><span class="ss"> students"</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Test set size: </span><span class="sc">{</span><span class="bu">len</span>(X_test)<span class="sc">}</span><span class="ss"> students"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training set size: 225 students
Test set size: 75 students</code></pre>
</div>
</div>
<p><strong>Why split the data?</strong></p>
<p>Remember from Week 2: Splitting the data measures <strong>generalization</strong>. The training set is used to build the model (train the tree), and the test set checks if the model works on students it has never seen before.</p>
<p>If the model performs much better on training data than test data, it means the model memorized the training examples rather than learning general patterns.</p>
</section>
<section id="step-2-create-and-train-the-decision-tree" class="level3">
<h3 class="anchored" data-anchor-id="step-2-create-and-train-the-decision-tree">Step 2: Create and train the decision tree</h3>
<div id="fb9d921e" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.tree <span class="im">import</span> DecisionTreeClassifier</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a decision tree with default settings</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>tree <span class="op">=</span> DecisionTreeClassifier(random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Train the tree on the training data</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>tree.fit(X_train, y_train)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Decision tree trained successfully!"</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Tree depth: </span><span class="sc">{</span>tree<span class="sc">.</span>get_depth()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of leaves: </span><span class="sc">{</span>tree<span class="sc">.</span>get_n_leaves()<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Decision tree trained successfully!
Tree depth: 7
Number of leaves: 39</code></pre>
</div>
</div>
<p><strong>Understanding the code:</strong></p>
<p><strong>Importing the classifier:</strong> - <code>from sklearn.tree import DecisionTreeClassifier</code> imports the decision tree class from scikit-learn - Similar to how we imported Ridge and LogisticRegression in Week 3</p>
<p><strong>Creating the model:</strong> - <code>tree = DecisionTreeClassifier(random_state=42)</code> creates a new tree with default settings - <code>random_state=42</code> ensures reproducible results (same as the random seed in data generation) - Without any parameters specified, the tree can grow until all leaves are pure (perfectly separate the classes)</p>
<p><strong>Training the model:</strong> - <code>tree.fit(X_train, y_train)</code> trains the tree on the training data - This is where the tree building happens - the algorithm finds the best questions to ask - The <code>.fit()</code> method modifies the <code>tree</code> object to store the learned structure</p>
<p><strong>Inspecting the trained tree:</strong> - <code>tree.get_depth()</code> returns how deep the tree grew (longest path from root to any leaf) - <code>tree.get_n_leaves()</code> returns how many final decision points (leaves) exist - These methods help us understand the complexity of the learned tree</p>
<p><strong>What happens during training:</strong></p>
<p>When <code>.fit()</code> is called, the decision tree algorithm: 1. Looks at all the features and finds the best question to ask first (the one that best separates pass from fail) 2. Splits the students into two groups based on that question 3. For each group, it repeats: find the best question, split again 4. Keeps splitting until it reaches a stopping point</p>
<p>The algorithm tries every possible question it could ask (“Is attendance &gt; 65%?”, “Is attendance &gt; 66%?”, “Is quiz_avg &gt; 50?”, etc.) and picks the one that best separates the classes.</p>
<p><strong>Understanding tree depth:</strong> - <strong>Depth</strong> = the longest path from the root (first question) to any leaf (final decision) - The depth value tells us the maximum number of questions the tree can ask in a row for any student</p>
<p><strong>Understanding leaves:</strong> - <strong>Leaves</strong> are the end points of the tree where predictions are made - Each leaf contains some training students and predicts the majority class in that leaf</p>
</section>
<section id="step-3-evaluate-the-model" class="level3">
<h3 class="anchored" data-anchor-id="step-3-evaluate-the-model">Step 3: Evaluate the model</h3>
<div id="7abe7f5b" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate accuracy on training data</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>train_accuracy <span class="op">=</span> tree.score(X_train, y_train)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Training accuracy: </span><span class="sc">{</span>train_accuracy<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate accuracy on test data</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>test_accuracy <span class="op">=</span> tree.score(X_test, y_test)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Test accuracy: </span><span class="sc">{</span>test_accuracy<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training accuracy: 1.000
Test accuracy: 0.813</code></pre>
</div>
</div>
<p><strong>Interpreting the results:</strong></p>
<p>The training accuracy shows how well the tree predicts the students it was trained on. The test accuracy shows how well it predicts new students it has never seen.</p>
<p><strong>Perfect or near-perfect training accuracy</strong> (like 1.000 or 0.99+) means the tree has grown deep enough to memorize most or all of the training examples. This is common with decision trees when depth isn’t limited.</p>
<p>The test accuracy is what really matters - it indicates if the model learned general patterns or just memorized training data.</p>
<p><strong>Note:</strong> On this clean synthetic data, the tree might perform well even without depth restrictions. With real-world messy data, unlimited depth often leads to overfitting. The textbook demonstrates this with datasets like Breast Cancer and make_moons.</p>
</section>
<section id="step-4-making-predictions" class="level3">
<h3 class="anchored" data-anchor-id="step-4-making-predictions">Step 4: Making predictions</h3>
<p>This section examines how the tree makes predictions for a few test students:</p>
<div id="b7541b01" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at first 5 test students</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>sample_students <span class="op">=</span> X_test.head(<span class="dv">5</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>sample_predictions <span class="op">=</span> tree.predict(sample_students)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>actual_results <span class="op">=</span> y_test.head(<span class="dv">5</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a comparison DataFrame</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>comparison <span class="op">=</span> pd.DataFrame({</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"attendance"</span>: sample_students[<span class="st">"attendance"</span>].values,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"homework_rate"</span>: sample_students[<span class="st">"homework_rate"</span>].values,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"quiz_avg"</span>: sample_students[<span class="st">"quiz_avg"</span>].values,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"exam_avg"</span>: sample_students[<span class="st">"exam_avg"</span>].values,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"predicted"</span>: sample_predictions,</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"actual"</span>: actual_results.values</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Sample predictions on test students:"</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(comparison)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">✓ = correct prediction, ✗ = incorrect prediction"</span>)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, row <span class="kw">in</span> comparison.iterrows():</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>    symbol <span class="op">=</span> <span class="st">"✓"</span> <span class="cf">if</span> row[<span class="st">"predicted"</span>] <span class="op">==</span> row[<span class="st">"actual"</span>] <span class="cf">else</span> <span class="st">"✗"</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"Student </span><span class="sc">{</span>i<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>symbol<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample predictions on test students:
   attendance  homework_rate  quiz_avg  exam_avg predicted actual
0          88             94        96        49      fail   pass
1          78             61        90        41      fail   fail
2          97             75        45        70      pass   fail
3          63             55        92        45      pass   fail
4          91             64        48        86      fail   fail

✓ = correct prediction, ✗ = incorrect prediction
Student 0: ✗
Student 1: ✓
Student 2: ✗
Student 3: ✗
Student 4: ✓</code></pre>
</div>
</div>
<p><strong>How the tree makes these predictions:</strong></p>
<p>For each student, the tree: 1. Starts at the root and asks the first question (“Is exam_avg &gt; 65?”) 2. Based on the answer, moves to the left or right branch 3. Asks another question at that node 4. Continues following branches until reaching a leaf 5. Predicts the class that most training students in that leaf had</p>
<p>The tree doesn’t use a formula like linear models. It follows a path of questions until it reaches a decision.</p>
</section>
</section>
<section id="part-3-exploring-the-max_depth-parameter" class="level2">
<h2 class="anchored" data-anchor-id="part-3-exploring-the-max_depth-parameter">Part 3: Exploring the max_depth Parameter</h2>
<p>The most important parameter for controlling decision tree complexity is <strong>max_depth</strong>. It controls how many questions the tree is allowed to ask in sequence.</p>
<p>Understanding depth levels: - <strong>Depth 1</strong>: Can only ask ONE question total (“Is exam_avg &gt; 70?”) - <strong>Depth 2</strong>: Can ask a question, then ask ONE follow-up question for each answer - <strong>Depth 3</strong>: Can ask three questions in a row - <strong>No limit</strong>: Can ask as many questions as needed to perfectly separate the training data</p>
<p><strong>Deeper trees</strong> = more questions = more detailed decisions = more complex model</p>
<p><strong>Shallower trees</strong> = fewer questions = simpler decisions = simpler model</p>
<p>This section trains trees with different depth limits and compares them:</p>
<div id="a4fb3304" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Train trees with different max_depth values</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>depths <span class="op">=</span> [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="va">None</span>]  <span class="co"># None means no limit</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> []</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> depth <span class="kw">in</span> depths:</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create and train a tree with this depth</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    tree <span class="op">=</span> DecisionTreeClassifier(max_depth<span class="op">=</span>depth, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    tree.fit(X_train, y_train)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Evaluate on both training and test sets</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    train_acc <span class="op">=</span> tree.score(X_train, y_train)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    test_acc <span class="op">=</span> tree.score(X_test, y_test)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Store results</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>    depth_label <span class="op">=</span> <span class="st">"unlimited"</span> <span class="cf">if</span> depth <span class="kw">is</span> <span class="va">None</span> <span class="cf">else</span> depth</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    results.append({</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>        <span class="st">"max_depth"</span>: depth_label,</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>        <span class="st">"num_leaves"</span>: tree.get_n_leaves(),</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">"training_accuracy"</span>: train_acc,</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>        <span class="st">"test_accuracy"</span>: test_acc</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Display results as a table</span></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>results_df <span class="op">=</span> pd.DataFrame(results)</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Comparison of trees with different max_depth:"</span>)</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(results_df.to_string(index<span class="op">=</span><span class="va">False</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Comparison of trees with different max_depth:
max_depth  num_leaves  training_accuracy  test_accuracy
        1           2           0.791111       0.840000
        2           4           0.795556       0.760000
        3           8           0.840000       0.800000
        5          24           0.951111       0.826667
unlimited          39           1.000000       0.813333</code></pre>
</div>
</div>
<p><strong>Understanding the code:</strong></p>
<p><strong>Setting up the experiment:</strong> - <code>depths = [1, 2, 3, 5, None]</code> creates a list of different max_depth values to try - <code>None</code> means no depth limit - the tree can grow as deep as needed - <code>results = []</code> creates an empty list to store results from each tree</p>
<p><strong>Looping through depth values:</strong> - <code>for depth in depths:</code> repeats the process for each depth value - Each iteration trains a new tree with that specific depth limit</p>
<p><strong>Creating and training each tree:</strong> - <code>tree = DecisionTreeClassifier(max_depth=depth, random_state=42)</code> creates a tree with the current depth limit - <code>tree.fit(X_train, y_train)</code> trains that tree on the training data - Each tree is independent - we’re not modifying the same tree</p>
<p><strong>Evaluating each tree:</strong> - <code>train_acc = tree.score(X_train, y_train)</code> calculates accuracy on training data - <code>test_acc = tree.score(X_test, y_test)</code> calculates accuracy on test data - We evaluate on both sets to detect overfitting</p>
<p><strong>Storing results:</strong> - <code>depth_label = "unlimited" if depth is None else depth</code> converts <code>None</code> to the string “unlimited” for readability - <code>results.append({...})</code> adds a dictionary with all results for this depth to the list - <code>tree.get_n_leaves()</code> gets the number of leaves from the trained tree</p>
<p><strong>Creating the comparison table:</strong> - <code>results_df = pd.DataFrame(results)</code> converts the list of dictionaries into a DataFrame - This creates a table where each row is one tree (one depth value) - <code>.to_string(index=False)</code> displays the table without row numbers</p>
<p><strong>Interpreting the table:</strong></p>
<p>Look at the patterns: 1. <strong>Number of leaves increases</strong> with depth - more questions → more possible outcomes 2. <strong>Training accuracy generally increases</strong> with depth - more questions → better fit to training data 3. <strong>Test accuracy doesn’t always increase</strong> - in fact, depth=1 achieves the highest test accuracy (0.840) on this dataset</p>
<p><strong>Key insights:</strong> - On this clean synthetic dataset, a very simple tree (depth=1) performs surprisingly well on test data. This happens because the data has clear, simple patterns - asking just one question (“Is exam_avg high enough?”) captures most of the signal. - A tree with unlimited depth achieves perfect training accuracy (1.000) but lower test accuracy (0.813), showing some overfitting. - Depth=5 provides a good balance with strong test performance (0.827) and more detailed decision-making.</p>
<p><strong>Important note:</strong> This pattern is specific to this clean, synthetic dataset where relationships are straightforward. On real-world messy data (like the Breast Cancer dataset in the textbook), very shallow trees typically underfit, and you’ll see more obvious benefits from moderate depths like 3-5.</p>
<p>This is similar to the k parameter in kNN and the alpha/C parameters in linear models - they all control the balance between simplicity and complexity.</p>
<section id="visualizing-the-comparison" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-the-comparison">Visualizing the comparison</h3>
<div id="ac308f30" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a visualization comparing train vs test accuracy</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert depth labels to numeric for plotting (unlimited → -1 for positioning)</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>x_positions <span class="op">=</span> [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">6</span>]  <span class="co"># Position "unlimited" at 6</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>x_labels <span class="op">=</span> [<span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span>, <span class="st">"5"</span>, <span class="st">"unlimited"</span>]</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>ax.plot(x_positions, results_df[<span class="st">"training_accuracy"</span>], </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>        marker<span class="op">=</span><span class="st">'o'</span>, label<span class="op">=</span><span class="st">'Training Accuracy'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>ax.plot(x_positions, results_df[<span class="st">"test_accuracy"</span>], </span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>        marker<span class="op">=</span><span class="st">'s'</span>, label<span class="op">=</span><span class="st">'Test Accuracy'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"max_depth"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Accuracy"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Decision Tree Performance vs. max_depth"</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(x_positions)</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>ax.set_xticklabels(x_labels)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>ax.legend(fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>ax.set_ylim([<span class="fl">0.7</span>, <span class="fl">1.05</span>])</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="week-5-demo_files/figure-html/cell-8-output-1.png" width="951" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>What this visualization shows:</strong></p>
<p>This plot shows the relationship between tree depth and performance: - <strong>Left side (depth=1)</strong>: Very simple tree with surprisingly high test accuracy (0.840) - one good question captures most of the pattern - <strong>Middle (depth=3-5)</strong>: More complex trees with strong test accuracy, providing more detailed decision boundaries - <strong>Right side (unlimited)</strong>: Complex tree with perfect training accuracy (1.000) but lower test accuracy (0.813), showing overfitting</p>
<p>On this dataset, depth=1 actually achieves the best test accuracy. This demonstrates that simpler models can outperform complex ones when the data has clear patterns. The unlimited depth tree memorizes training data (perfect training accuracy) but doesn’t generalize as well.</p>
<p><strong>Note about this dataset:</strong> This student performance data has clean, straightforward relationships. On real-world messy data (like the Breast Cancer dataset in the textbook), very shallow trees typically underfit and you’ll see clearer benefits from moderate depths. The textbook shows more dramatic overfitting patterns with complex, noisy datasets.</p>
</section>
</section>
<section id="part-4-understanding-feature-importance" class="level2">
<h2 class="anchored" data-anchor-id="part-4-understanding-feature-importance">Part 4: Understanding Feature Importance</h2>
<p>One of the most useful aspects of decision trees is <strong>feature importance</strong> - they indicate which features matter most for making predictions.</p>
<p>Feature importance is a number between 0 and 1 for each feature: - <strong>0</strong> means the feature was never used in the tree - <strong>1</strong> would mean this feature alone perfectly separates the classes - <strong>Higher values</strong> mean the feature is more important - The importances always <strong>sum to 1.0</strong></p>
<p>This section extracts and visualizes feature importance from one of the trees:</p>
<div id="9f849641" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Train a tree with reasonable depth for interpretation</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>tree <span class="op">=</span> DecisionTreeClassifier(max_depth<span class="op">=</span><span class="dv">5</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>tree.fit(X_train, y_train)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract feature importances</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>importances <span class="op">=</span> tree.feature_importances_</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>feature_names <span class="op">=</span> X_train.columns</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Display as a table</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>importance_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Feature"</span>: feature_names,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Importance"</span>: importances</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>}).sort_values(<span class="st">"Importance"</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Feature Importance Rankings:"</span>)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(importance_df.to_string(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Total importance: </span><span class="sc">{</span>importances<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.3f}</span><span class="ss"> (should always be 1.0)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Feature Importance Rankings:
      Feature  Importance
     exam_avg    0.538999
     quiz_avg    0.247003
homework_rate    0.163215
   attendance    0.050783

Total importance: 1.000 (should always be 1.0)</code></pre>
</div>
</div>
<p><strong>Understanding the code:</strong></p>
<p><strong>Training a tree for analysis:</strong> - <code>tree = DecisionTreeClassifier(max_depth=5, random_state=42)</code> creates a tree with limited depth - We use <code>max_depth=5</code> to get a reasonably complex but not overfitted tree - <code>tree.fit(X_train, y_train)</code> trains this tree on the training data</p>
<p><strong>Extracting feature importance:</strong> - <code>importances = tree.feature_importances_</code> gets the importance score for each feature - This is a built-in property that scikit-learn calculates after training - Returns a numpy array with one value per feature</p>
<p><strong>Getting feature names:</strong> - <code>feature_names = X_train.columns</code> extracts the column names from our DataFrame - We need these to label which importance value corresponds to which feature - Without this, we’d just have numbers with no context</p>
<p><strong>Creating a readable table:</strong> - <code>pd.DataFrame({...})</code> creates a DataFrame pairing feature names with their importance values - <code>"Feature": feature_names</code> creates the first column with feature names - <code>"Importance": importances</code> creates the second column with importance scores - <code>.sort_values("Importance", ascending=False)</code> sorts so the most important features appear first</p>
<p><strong>Displaying results:</strong> - <code>.to_string(index=False)</code> prints the table without row numbers - <code>importances.sum()</code> adds up all importance values to verify they sum to 1.0 - The sum should always be 1.0 - this is a good sanity check</p>
<p><strong>What these numbers mean:</strong></p>
<p>Feature importance indicates <strong>how much each feature contributed to the tree’s decisions</strong>: - exam_avg has importance 0.539, meaning about 54% of the tree’s decision-making power comes from exam scores - attendance has importance 0.051, meaning attendance was rarely used or had weak splits</p>
<p>The tree calculates this by looking at: 1. How often each feature was used for splits 2. How much each split improved the predictions 3. How many training samples were affected by each split</p>
<p>Features used higher in the tree (for the first questions) and features that create good separations get higher importance scores.</p>
<section id="visualizing-feature-importance" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-feature-importance">Visualizing feature importance</h3>
<div id="c23c32e1" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a horizontal bar plot</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Sort features by importance for better visualization</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>sorted_idx <span class="op">=</span> np.argsort(importances)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>sorted_features <span class="op">=</span> feature_names[sorted_idx]</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>sorted_importances <span class="op">=</span> importances[sorted_idx]</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create bars</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>ax.barh(<span class="bu">range</span>(<span class="bu">len</span>(sorted_features)), sorted_importances, color<span class="op">=</span><span class="st">'steelblue'</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>ax.set_yticks(<span class="bu">range</span>(<span class="bu">len</span>(sorted_features)))</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>ax.set_yticklabels(sorted_features)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Importance"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Feature"</span>, fontsize<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Feature Importance in Decision Tree"</span>, fontsize<span class="op">=</span><span class="dv">14</span>)</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Add value labels on bars</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, v <span class="kw">in</span> <span class="bu">enumerate</span>(sorted_importances):</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>    ax.text(v <span class="op">+</span> <span class="fl">0.01</span>, i, <span class="ss">f'</span><span class="sc">{</span>v<span class="sc">:.3f}</span><span class="ss">'</span>, va<span class="op">=</span><span class="st">'center'</span>)</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="week-5-demo_files/figure-html/cell-10-output-1.png" width="948" height="566" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpreting the feature importance plot:</strong></p>
<p>This visualization shows which features the tree considers most important for predicting pass/fail: - <strong>Features on top</strong> (longer bars) are more important - <strong>Features on bottom</strong> (shorter bars) are less important</p>
<p>In this student data, exam_avg and quiz_avg are likely most important, which makes sense - these are strong predictors of the final grade. Homework and attendance might have lower importance if they’re less directly related to passing.</p>
</section>
<section id="comparing-to-linear-model-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="comparing-to-linear-model-coefficients">Comparing to Linear Model Coefficients</h3>
<p>Remember from Week 3: Linear models also show feature importance through their <strong>coefficients</strong> (weights). How do these compare?</p>
<p><strong>Decision Tree Feature Importance:</strong> - Always <strong>positive</strong> (between 0 and 1) - Indicates <strong>how much the feature matters</strong> - Does NOT indicate direction (whether high values mean pass or fail) - Changes based on tree structure and splits</p>
<p><strong>Linear Model Coefficients:</strong> - Can be <strong>positive or negative</strong> - Positive = “as this feature increases, prediction increases” - Negative = “as this feature increases, prediction decreases” - Shows both importance AND direction</p>
<p>Both are useful. Trees indicate “what matters most” while linear models indicate “what matters and how.”</p>
</section>
</section>
<section id="part-5-comparing-decision-trees-to-other-models" class="level2">
<h2 class="anchored" data-anchor-id="part-5-comparing-decision-trees-to-other-models">Part 5: Comparing Decision Trees to Other Models</h2>
<p>This section compares decision trees to the other algorithms learned in previous weeks:</p>
<section id="decision-trees-vs.-k-nearest-neighbors-knn" class="level3">
<h3 class="anchored" data-anchor-id="decision-trees-vs.-k-nearest-neighbors-knn">Decision Trees vs.&nbsp;k-Nearest Neighbors (kNN)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 17%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>kNN</th>
<th>Decision Trees</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Training time</td>
<td>Fast (just stores data)</td>
<td>Slower (builds tree structure)</td>
</tr>
<tr class="even">
<td>Prediction time</td>
<td>Slow (searches all data)</td>
<td>Fast (follows one path)</td>
</tr>
<tr class="odd">
<td>Memory usage</td>
<td>High (stores all training data)</td>
<td>Low (stores tree structure only)</td>
</tr>
<tr class="even">
<td>Interpretability</td>
<td>Hard to explain</td>
<td>Easy (can visualize tree)</td>
</tr>
<tr class="odd">
<td>Data scaling</td>
<td>Required</td>
<td>Not required</td>
</tr>
<tr class="even">
<td>Parameters</td>
<td>k (number of neighbors)</td>
<td>max_depth, max_leaves, etc.</td>
</tr>
</tbody>
</table>
</section>
<section id="decision-trees-vs.-linear-models" class="level3">
<h3 class="anchored" data-anchor-id="decision-trees-vs.-linear-models">Decision Trees vs.&nbsp;Linear Models</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 38%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Linear Models</th>
<th>Decision Trees</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model type</td>
<td>Global formula</td>
<td>Local rules</td>
</tr>
<tr class="even">
<td>Decision boundary</td>
<td>Straight line</td>
<td>Axis-parallel rectangles</td>
</tr>
<tr class="odd">
<td>Feature interactions</td>
<td>Must be specified</td>
<td>Automatic</td>
</tr>
<tr class="even">
<td>Interpretability</td>
<td>Can see coefficients</td>
<td>Can visualize tree</td>
</tr>
<tr class="odd">
<td>Data scaling</td>
<td>Required</td>
<td>Not required</td>
</tr>
<tr class="even">
<td>Overfitting tendency</td>
<td>Lower (with regularization)</td>
<td>Higher (without limits)</td>
</tr>
</tbody>
</table>
</section>
<section id="when-to-use-decision-trees" class="level3">
<h3 class="anchored" data-anchor-id="when-to-use-decision-trees">When to Use Decision Trees</h3>
<p><strong>Decision trees work well when:</strong> - Features are on different scales (no scaling needed) - You have a mix of different feature types (numeric, categorical) - You need an interpretable model you can explain to non-technical people - Feature interactions matter (trees capture these automatically) - You want to see which features are most important</p>
<p><strong>Use other models when:</strong> - You need the absolute best accuracy (ensembles like Random Forests often beat single trees) - Your data is high-dimensional and sparse (like text) - linear models often work better - You have very little training data - simpler models might generalize better</p>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<section id="key-takeaways" class="level3">
<h3 class="anchored" data-anchor-id="key-takeaways">Key Takeaways</h3>
<ol type="1">
<li>Decision trees learn a hierarchy of if/else questions during training, then follow that path to make predictions</li>
<li>The <code>max_depth</code> parameter controls tree complexity: deeper trees can ask more questions</li>
<li>Feature importance shows which features the tree used most for making decisions</li>
<li>Trees don’t require feature scaling, unlike kNN and linear models</li>
<li>On clean synthetic data, trees may not show obvious overfitting; real-world messy data often does</li>
<li>Trees are easy to interpret but can overfit on complex data without proper depth limits</li>
</ol>
</section>
<section id="the-challenge-with-single-decision-trees" class="level3">
<h3 class="anchored" data-anchor-id="the-challenge-with-single-decision-trees">The Challenge with Single Decision Trees</h3>
<p>Single decision trees have one major weakness: <strong>they tend to overfit on complex data</strong>. When you have noisy, real-world data, trees often memorize training examples rather than learning general patterns.</p>
<p>On this clean synthetic student data, overfitting isn’t a major problem. But on datasets like: - Medical diagnosis (lots of noise and uncertainty) - Customer behavior (many random factors) - Image classification (high-dimensional, complex patterns)</p>
<p>…single trees often struggle.</p>
</section>
<section id="enter-ensembles-the-solution" class="level3">
<h3 class="anchored" data-anchor-id="enter-ensembles-the-solution">Enter Ensembles: The Solution</h3>
<p>The textbook introduces two powerful ensemble methods that fix this problem by <strong>combining many trees</strong>:</p>
<p><strong>Random Forests:</strong> - Builds hundreds of trees, each slightly different - Each tree sees a random subset of the data and features - Averages their predictions - Result: Much more robust, less overfitting</p>
<p><strong>Gradient Boosting:</strong> - Builds trees one at a time - Each new tree focuses on correcting the previous tree’s mistakes - Result: Often the best performance, but requires careful tuning</p>
<p>These ensemble methods keep all the benefits of trees (no scaling, interpretable, handles mixed features) while dramatically reducing overfitting.</p>
</section>
<section id="further-reading-in-the-textbook" class="level3">
<h3 class="anchored" data-anchor-id="further-reading-in-the-textbook">Further Reading in the Textbook</h3>
<p>As you read Chapter 2’s decision tree section, pay attention to:</p>
<ol type="1">
<li><strong>Tree Visualization (export_graphviz)</strong>
<ul>
<li>How to actually see the tree structure</li>
<li>Understanding nodes, branches, and leaves visually</li>
<li>The Breast Cancer tree example</li>
</ul></li>
<li><strong>More Control Parameters</strong>
<ul>
<li>max_leaf_nodes, min_samples_split, min_samples_leaf</li>
<li>Different ways to prevent overfitting</li>
</ul></li>
<li><strong>Regression Trees</strong>
<ul>
<li>DecisionTreeRegressor for predicting numbers</li>
<li>The RAM price time-series example</li>
<li>Key limitation: can’t extrapolate beyond training range</li>
</ul></li>
<li><strong>Overfitting Examples</strong>
<ul>
<li>The make_moons dataset showing clear overfitting</li>
<li>Breast Cancer dataset with 100% training accuracy</li>
<li>Why limiting depth helps</li>
</ul></li>
<li><strong>Random Forests &amp; Gradient Boosting</strong>
<ul>
<li>These are where trees become truly powerful</li>
<li>Currently among the most widely used ML methods</li>
<li>Often win Kaggle competitions</li>
</ul></li>
</ol>
<p>The demo provided the practical foundation - how to build and use decision trees. The textbook provides the complete picture - when they fail, how to fix those failures, and how to make them even more powerful.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/SCTCC-Computer-Programming\.github\.io\/cmsc-2208\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function() {
    var elements = document.querySelectorAll('[aria-label]');
    for (var i = 0; i < elements.length; i++) {
      var ariaLabel = elements[i].getAttribute('aria-label');
      elements[i].setAttribute('data-bs-title', ariaLabel);
      elements[i].setAttribute('data-bs-toggle', 'tooltip');
      elements[i].setAttribute('data-bs-placement', 'bottom');
    }
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
  });
</script>




</body></html>